# 第一课

褚则伟 zeweichu@gmail.com

[参考资料 reference](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html)


什么是PyTorch?
================

PyTorch是一个基于Python的科学计算库，它有以下特点:

- 类似于NumPy，但是它可以使用GPU
- 可以用它定义深度学习模型，可以灵活地进行深度学习模型的训练和使用

Tensors
---------------


Tensor类似与NumPy的ndarray，唯一的区别是Tensor可以在GPU上加速运算。


In [1]:
from __future__ import print_function
import torch

构造一个未初始化的5x3矩阵:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.7339e+30, 1.4347e-19],
        [2.7909e+23, 1.8037e+28, 1.7237e+25],
        [9.1041e-12, 6.2609e+22, 4.7428e+30],
        [3.8001e-39, 0.0000e+00, 0.0000e+00]])


构建一个随机初始化的矩阵:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4821, 0.3854, 0.8517],
        [0.7962, 0.0632, 0.5409],
        [0.8891, 0.6112, 0.7829],
        [0.0715, 0.8069, 0.2608],
        [0.3292, 0.0119, 0.2759]])


构建一个全部为0，类型为long的矩阵:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


从数据直接直接构建tensor:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


也可以从一个已有的tensor构建一个tensor。这些方法会重用原来tensor的特征，例如，数据类型，除非提供新的数据。

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4793, -2.4772,  0.9738],
        [ 2.0328,  1.3981,  1.7509],
        [-0.7931, -0.0291, -0.6803],
        [-1.2944, -0.7352, -0.9346],
        [ 0.5917, -0.5149, -1.8149]])


得到tensor的形状:

In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>注意</h4><p>``torch.Size`` 返回的是一个tuple</p></div>

Operations


有很多种tensor运算。我们先介绍加法运算。



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


另一种着加法的写法


In [9]:
print(torch.add(x, y))

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


加法：把输出作为一个变量

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


in-place加法

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


<div class="alert alert-info"><h4>注意</h4><p>任何in-place的运算都会以``_``结尾。
    举例来说：``x.copy_(y)``, ``x.t_()``, 会改变 ``x``。</p></div>

各种类似NumPy的indexing都可以在PyTorch tensor上面使用。


In [12]:
print(x[:, 1])

tensor([-2.4772,  1.3981, -0.0291, -0.7352, -0.5149])


Resizing: 如果你希望resize/reshape一个tensor，可以使用``torch.view``：

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个只有一个元素的tensor，使用``.item()``方法可以把里面的value变成Python数值。

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4726])
0.4726296067237854


**更多阅读**


  各种Tensor operations, 包括transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers在
  `<https://pytorch.org/docs/torch>`.

Numpy和Tensor之间的转化
------------

在Torch Tensor和NumPy array之间相互转化非常容易。

Torch Tensor和NumPy array会共享内存，所以改变其中一项也会改变另一项。

把Torch Tensor转变成NumPy Array


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


改变numpy array里面的值。

In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


把NumPy ndarray转成Torch Tensor

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有CPU上的Tensor都支持转成numpy或者从numpy转成Tensor。

CUDA Tensors
------------

使用``.to``方法，Tensor可以被移动到别的device上。



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


热身: 用numpy实现两层神经网络
--------------

一个全连接ReLU神经网络，一个隐藏层，没有bias。用来从x预测y，使用L2 Loss。

这一实现完全使用numpy来计算前向神经网络，loss，和反向传播。

numpy ndarray是一个普通的n维array。它不知道任何关于深度学习或者梯度(gradient)的知识，也不知道计算图(computation graph)，只是一种用来计算数学运算的数据结构。



In [20]:
import numpy as np

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    
    # loss = (y_pred - y) ** 2
    grad_y_pred = 2.0 * (y_pred - y)
    # 
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 34399246.46047344
1 29023199.257758312
2 25155679.85447208
3 20344203.603057466
4 14771404.625789404
5 9796072.99431371
6 6194144.749997159
7 3948427.3657580013
8 2637928.1726997104
9 1879876.2597949505
10 1424349.925182723
11 1131684.579785501
12 930879.9521737935
13 783503.167740541
14 669981.8287784329
15 579151.6288421676
16 504610.5781504087
17 442295.18952143926
18 389647.44224490353
19 344718.3535892912
20 306120.2245707266
21 272728.24885829526
22 243778.8617292929
23 218485.92082002352
24 196304.70602822883
25 176774.2980280186
26 159509.34934842546
27 144200.52956072442
28 130597.06878493169
29 118484.47548850597
30 107661.24303895692
31 97973.75762285746
32 89291.0096051952
33 81500.46898789635
34 74477.4654945682
35 68139.90452489533
36 62418.87519034026
37 57241.53801123622
38 52545.34658231941
39 48280.5552386464
40 44399.73653914068
41 40864.495617471934
42 37640.08489317873
43 34695.77852549495
44 32004.894008637555
45 29545.09481447049
46 27292.93700341219
47 25232.8

367 0.0004326546423136559
368 0.0004116382458083261
369 0.0003916440959886334
370 0.0003726296356534275
371 0.0003545443586216977
372 0.000337347352488608
373 0.00032099061370803334
374 0.0003054229784132819
375 0.00029061647064382485
376 0.0002765299098361774
377 0.0002631327221101076
378 0.0002503865963973947
379 0.0002382599294869431
380 0.00022672670184804494
381 0.00021575299560298047
382 0.00020531375263207438
383 0.000195381616896771
384 0.00018593500698085453
385 0.00017694494225329907
386 0.00016839225855899982
387 0.00016025517275686525
388 0.00015251350815142156
389 0.0001451491411549753
390 0.0001381428245892601
391 0.00013147417414693054
392 0.00012512977608770297
393 0.00011909308605343111
394 0.00011334857979979945
395 0.00010788480695473414
396 0.00010268704883570024
397 9.773868892276339e-05
398 9.303020197524704e-05
399 8.85491663624475e-05
400 8.428485316645869e-05
401 8.022778747190388e-05
402 7.636668153099922e-05
403 7.269236014951034e-05
404 6.919607836124983e-05


PyTorch: Tensors
----------------

这次我们使用PyTorch tensors来创建前向神经网络，计算损失，以及反向传播。

一个PyTorch Tensor很像一个numpy的ndarray。但是它和numpy ndarray最大的区别是，PyTorch Tensor可以在CPU或者GPU上运算。如果想要在GPU上运算，就需要把Tensor换成cuda类型。


In [21]:
import torch


dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Randomly initialize weights
w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    # Update weights using gradient descent
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 31704728.0
1 25331164.0
2 22378086.0
3 19262238.0
4 15348289.0
5 11017595.0
6 7356282.0
7 4705923.5
8 3027346.5
9 2012536.375
10 1409662.25
11 1041771.75
12 807321.0625
13 649262.0
14 536533.1875
15 451980.875
16 385983.53125
17 332925.53125
18 289368.1875
19 253030.78125
20 222354.703125
21 196214.3125
22 173766.515625
23 154378.140625
24 137539.375
25 122867.1015625
26 110037.3515625
27 98769.4921875
28 88842.109375
29 80063.15625
30 72279.015625
31 65361.66796875
32 59195.42578125
33 53687.4453125
34 48757.57421875
35 44338.4453125
36 40370.34765625
37 36803.1484375
38 33587.4453125
39 30684.1640625
40 28059.435546875
41 25683.255859375
42 23528.814453125
43 21570.8515625
44 19792.4296875
45 18175.244140625
46 16704.6640625
47 15364.2578125
48 14141.7509765625
49 13026.609375
50 12007.3115234375
51 11075.3896484375
52 10221.8857421875
53 9439.876953125
54 8722.13671875
55 8063.46826171875
56 7458.20703125
57 6901.8876953125
58 6390.34375
59 5919.4794921875
60 5485.79345703125
61 5

375 0.0002844816190190613
376 0.00027625024085864425
377 0.0002687727683223784
378 0.0002608516369946301
379 0.00025311342324130237
380 0.0002469048195052892
381 0.00024049097555689514
382 0.0002342124644201249
383 0.00022811403323430568
384 0.00022231723414734006
385 0.0002166029589716345
386 0.00021077181736472994
387 0.00020510501053649932
388 0.00020020001102238894
389 0.0001948442222783342
390 0.00018990584067068994
391 0.00018529882072471082
392 0.00018070911755785346
393 0.00017650797963142395
394 0.00017214834224432707
395 0.0001683011942077428
396 0.00016451899136882275
397 0.00016050187696237117
398 0.00015686434926465154
399 0.00015321985119953752
400 0.0001501761726103723
401 0.00014639270375482738
402 0.00014274154091253877
403 0.0001396275474689901
404 0.0001364489580737427
405 0.00013346801279112697
406 0.00013024920190218836
407 0.00012755846546497196
408 0.00012532222899608314
409 0.0001224723382620141
410 0.00011974618973908946
411 0.00011740042100427672
412 0.0001144

简单的autograd

In [22]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)



PyTorch: Tensor和autograd
-------------------------------

PyTorch的一个重要功能就是autograd，也就是说只要定义了forward pass(前向神经网络)，计算了loss之后，PyTorch可以自动求导计算模型所有参数的梯度。

一个PyTorch的Tensor表示计算图中的一个节点。如果``x``是一个Tensor并且``x.requires_grad=True``那么``x.grad``是另一个储存着``x``当前梯度(相对于一个scalar，常常是loss)的向量。


In [23]:
import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N 是 batch size; D_in 是 input dimension;
# H 是 hidden dimension; D_out 是 output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# 创建随机的Tensor来保存输入和输出
# 设定requires_grad=False表示在反向传播的时候我们不需要计算gradient
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# 创建随机的Tensor和权重。
# 设置requires_grad=True表示我们希望反向传播的时候计算Tensor的gradient
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # 前向传播:通过Tensor预测y；这个和普通的神经网络的前向传播没有任何不同，
    # 但是我们不需要保存网络的中间运算结果，因为我们不需要手动计算反向传播。
    y_pred = x.mm(w1).clamp(min=0).mm(w2)

    # 通过前向传播计算loss
    # loss是一个形状为(1，)的Tensor
    # loss.item()可以给我们返回一个loss的scalar
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())

    # PyTorch给我们提供了autograd的方法做反向传播。如果一个Tensor的requires_grad=True，
    # backward会自动计算loss相对于每个Tensor的gradient。在backward之后，
    # w1.grad和w2.grad会包含两个loss相对于两个Tensor的gradient信息。
    loss.backward()

    # 我们可以手动做gradient descent(后面我们会介绍自动的方法)。
    # 用torch.no_grad()包含以下statements，因为w1和w2都是requires_grad=True，
    # 但是在更新weights之后我们并不需要再做autograd。
    # 另一种方法是在weight.data和weight.grad.data上做操作，这样就不会对grad产生影响。
    # tensor.data会我们一个tensor，这个tensor和原来的tensor指向相同的内存空间，
    # 但是不会记录计算图的历史。
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

0 31590738.0
1 34389704.0
2 44504280.0
3 52598508.0
4 46752264.0
5 27227634.0
6 10779343.0
7 3889138.75
8 1856397.875
9 1232127.25
10 967278.5
11 806383.9375
12 687169.25
13 591936.25
14 513579.40625
15 448339.5
16 393390.71875
17 346772.71875
18 306952.625
19 272743.90625
20 243250.578125
21 217760.4375
22 195513.75
23 176012.4375
24 158848.59375
25 143694.4375
26 130272.53125
27 118357.1328125
28 107732.5625
29 98245.9296875
30 89754.4375
31 82145.9765625
32 75299.703125
33 69130.7265625
34 63549.09375
35 58498.18359375
36 53914.7421875
37 49751.984375
38 45963.8515625
39 42512.19140625
40 39364.1484375
41 36486.7421875
42 33852.94921875
43 31441.951171875
44 29230.11328125
45 27200.080078125
46 25335.595703125
47 23618.97265625
48 22036.193359375
49 20575.412109375
50 19227.5078125
51 17980.865234375
52 16826.919921875
53 15756.392578125
54 14762.513671875
55 13839.58203125
56 12981.9228515625
57 12184.3896484375
58 11442.140625
59 10750.8681640625
60 10106.751953125
61 9505.8720703

394 0.005430158693343401
395 0.005243257619440556
396 0.005058295093476772
397 0.0048800683580338955
398 0.004707938991487026
399 0.004541801754385233
400 0.004385354463011026
401 0.0042332010343670845
402 0.0040851193480193615
403 0.003942274488508701
404 0.003809330752119422
405 0.0036788880825042725
406 0.0035530496388673782
407 0.0034328829497098923
408 0.003316469956189394
409 0.0032058244105428457
410 0.003095718566328287
411 0.002996482653543353
412 0.002896404592320323
413 0.002801347989588976
414 0.0027062646113336086
415 0.0026161009445786476
416 0.002530781552195549
417 0.002449025632813573
418 0.002370838774368167
419 0.002294242149218917
420 0.002220114693045616
421 0.002151642693206668
422 0.0020829373970627785
423 0.0020190104842185974
424 0.0019563380628824234
425 0.0018947365460917354
426 0.0018343634437769651
427 0.0017779992194846272
428 0.0017241643508896232
429 0.001670036930590868
430 0.0016198739176616073
431 0.0015696510672569275
432 0.0015243508387356997
433 0.


PyTorch: nn
-----------


这次我们使用PyTorch中nn这个库来构建网络。
用PyTorch autograd来构建计算图和计算gradients，
然后PyTorch会帮我们自动计算gradient。




In [24]:
import torch

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model as a sequence of layers. nn.Sequential
# is a Module which contains other Modules, and applies them in sequence to
# produce its output. Each Linear Module computes output from input using a
# linear function, and holds internal Tensors for its weight and bias.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# The nn package also contains definitions of popular loss functions; in this
# case we will use Mean Squared Error (MSE) as our loss function.
loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-4
for t in range(500):
    # Forward pass: compute predicted y by passing x to the model. Module objects
    # override the __call__ operator so you can call them like functions. When
    # doing so you pass a Tensor of input data to the Module and it produces
    # a Tensor of output data.
    y_pred = model(x)

    # Compute and print loss. We pass Tensors containing the predicted and true
    # values of y, and the loss function returns a Tensor containing the
    # loss.
    loss = loss_fn(y_pred, y)
    print(t, loss.item())

    # Zero the gradients before running the backward pass.
    model.zero_grad()

    # Backward pass: compute gradient of the loss with respect to all the learnable
    # parameters of the model. Internally, the parameters of each Module are stored
    # in Tensors with requires_grad=True, so this call will compute gradients for
    # all learnable parameters in the model.
    loss.backward()

    # Update the weights using gradient descent. Each parameter is a Tensor, so
    # we can access its gradients like we did before.
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

0 616.8349609375
1 570.4186401367188
2 530.6421508789062
3 495.7164001464844
4 464.91497802734375
5 437.1092834472656
6 411.87066650390625
7 388.5781555175781
8 367.105224609375
9 347.06768798828125
10 328.3486328125
11 310.6429748535156
12 294.08880615234375
13 278.54046630859375
14 263.8558044433594
15 249.83802795410156
16 236.52313232421875
17 223.8170166015625
18 211.7015380859375
19 200.13755798339844
20 189.1465301513672
21 178.6802520751953
22 168.74122619628906
23 159.31674194335938
24 150.35125732421875
25 141.79025268554688
26 133.63401794433594
27 125.89380645751953
28 118.53340148925781
29 111.54275512695312
30 104.91582489013672
31 98.65790557861328
32 92.7421646118164
33 87.18020629882812
34 81.94192504882812
35 77.01036834716797
36 72.3639144897461
37 67.99095916748047
38 63.88977813720703
39 60.036468505859375
40 56.426231384277344
41 53.05012512207031
42 49.88925552368164
43 46.92338943481445
44 44.14652633666992
45 41.54481887817383
46 39.10710144042969
47 36.8310813

364 0.00028583104722201824
365 0.000278460793197155
366 0.00027128090732730925
367 0.00026430474827066064
368 0.0002575131948105991
369 0.0002509095938876271
370 0.00024448230396956205
371 0.00023822381626814604
372 0.0002321432693861425
373 0.00022622810502070934
374 0.0002204657648690045
375 0.0002148632047465071
376 0.00020940121612511575
377 0.00020409838180057704
378 0.0001989272132050246
379 0.00019389843509998173
380 0.00018900231225416064
381 0.0001842392230173573
382 0.00017960301192943007
383 0.00017508988094050437
384 0.00017069902969524264
385 0.00016641429101582617
386 0.00016225305444095284
387 0.000158198265125975
388 0.00015424926823470742
389 0.000150404914165847
390 0.0001466635148972273
391 0.00014301779447123408
392 0.00013946628314442933
393 0.00013601550017483532
394 0.00013265143206808716
395 0.00012937198334839195
396 0.00012617645552381873
397 0.0001230676716659218
398 0.0001200390252051875
399 0.00011708753299899399
400 0.00011421682575019076
401 0.00011141804


PyTorch: optim
--------------

这一次我们不再手动更新模型的weights,而是使用optim这个包来帮助我们更新参数。
optim这个package提供了各种不同的模型优化方法，包括SGD+momentum, RMSProp, Adam等等。


In [25]:
import torch

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use Adam; the optim package contains many other
# optimization algoriths. The first argument to the Adam constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(500):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    print(t, loss.item())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()

0 791.6784057617188
1 772.9479370117188
2 754.7570190429688
3 737.1196899414062
4 719.9917602539062
5 703.4118041992188
6 687.2720947265625
7 671.5335083007812
8 656.197021484375
9 641.322265625
10 626.919189453125
11 612.9500732421875
12 599.3975219726562
13 586.327392578125
14 573.5608520507812
15 561.1778564453125
16 549.1342163085938
17 537.3661499023438
18 525.8930053710938
19 514.7115478515625
20 503.76434326171875
21 493.110107421875
22 482.747802734375
23 472.5677490234375
24 462.6549072265625
25 452.9748840332031
26 443.5308532714844
27 434.2815856933594
28 425.22064208984375
29 416.3988342285156
30 407.7718505859375
31 399.32879638671875
32 391.1062927246094
33 383.07781982421875
34 375.2408752441406
35 367.54071044921875
36 359.98126220703125
37 352.5944519042969
38 345.3690185546875
39 338.3002624511719
40 331.3758544921875
41 324.56463623046875
42 317.8782958984375
43 311.31622314453125
44 304.8724670410156
45 298.5438537597656
46 292.3463439941406
47 286.2505187988281
48 

429 4.1297284042229876e-05
430 3.9249673136509955e-05
431 3.7301993870642036e-05
432 3.545052823028527e-05
433 3.3691019780235365e-05
434 3.2015552278608084e-05
435 3.0420967959798872e-05
436 2.890893301810138e-05
437 2.74712383543374e-05
438 2.6098401576746255e-05
439 2.4797802325338125e-05
440 2.3561869966215454e-05
441 2.2385444026440382e-05
442 2.1267582269501872e-05
443 2.0203089661663398e-05
444 1.9192844774806872e-05
445 1.8230841305921786e-05
446 1.7318037862423807e-05
447 1.6449723261757754e-05
448 1.562457691761665e-05
449 1.4840144103800412e-05
450 1.409533797414042e-05
451 1.3387114449869841e-05
452 1.2712825991911814e-05
453 1.2073536709067412e-05
454 1.1465210263850167e-05
455 1.0887116332014557e-05
456 1.0337735147913918e-05
457 9.81609719019616e-06
458 9.320682693214621e-06
459 8.849255209497642e-06
460 8.402344064961653e-06
461 7.977385394042358e-06
462 7.57272437112988e-06
463 7.188868949015159e-06
464 6.824670890637208e-06
465 6.479081548604881e-06
466 6.150191438791


PyTorch: 自定义 nn Modules
--------------------------

我们可以定义一个模型，这个模型继承自nn.Module类。如果需要定义一个比Sequential模型更加复杂的模型，就需要定义nn.Module模型。



In [26]:
import torch


class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 656.6958618164062
1 608.1090087890625
2 566.172607421875
3 529.2335815429688
4 496.7382507324219
5 467.453125
6 440.5755310058594
7 416.12872314453125
8 393.6068420410156
9 372.708251953125
10 353.00006103515625
11 334.477783203125
12 316.97283935546875
13 300.36737060546875
14 284.6544189453125
15 269.65936279296875
16 255.33456420898438
17 241.66688537597656
18 228.60800170898438
19 216.09536743164062
20 204.13780212402344
21 192.75645446777344
22 181.89234924316406
23 171.58370971679688
24 161.7939453125
25 152.4780731201172
26 143.59371948242188
27 135.14727783203125
28 127.13992309570312
29 119.55585479736328
30 112.37797546386719
31 105.62073516845703
32 99.24383544921875
33 93.24134826660156
34 87.58341979980469
35 82.25212860107422
36 77.24210357666016
37 72.55087280273438
38 68.1427230834961
39 64.00277709960938
40 60.1308479309082
41 56.49887466430664
42 53.0952033996582
43 49.906524658203125
44 46.91959762573242
45 44.11970520019531
46 41.50297164916992
47 39.0628700256347

375 0.0006505012279376388
376 0.0006343786371871829
377 0.0006186614627949893
378 0.0006033276440575719
379 0.0005883832345716655
380 0.0005738206673413515
381 0.0005596213741227984
382 0.0005457888473756611
383 0.0005322962533682585
384 0.0005191444652155042
385 0.000506328884512186
386 0.0004938290221616626
387 0.00048163760220631957
388 0.0004697689728345722
389 0.0004582055553328246
390 0.00044691533548757434
391 0.00043590739369392395
392 0.0004251690406817943
393 0.0004147063591517508
394 0.00040450665983371437
395 0.0003945553908124566
396 0.0003848606429528445
397 0.00037539892946369946
398 0.0003661849768832326
399 0.00035720854066312313
400 0.000348439411027357
401 0.0003398970584385097
402 0.00033156739664264023
403 0.0003234421892557293
404 0.0003155224258080125
405 0.00030779733788222075
406 0.0003002593875862658
407 0.00029291390092112124
408 0.00028574312455020845
409 0.0002787590492516756
410 0.000271946337306872
411 0.00026530082686804235
412 0.00025882109184749424
413

# FizzBuzz

FizzBuzz是一个简单的小游戏。游戏规则如下：从1开始往上数数，当遇到3的倍数的时候，说fizz，当遇到5的倍数，说buzz，当遇到15的倍数，就说fizzbuzz，其他情况下则正常数数。

我们可以写一个简单的小程序来决定要返回正常数值还是fizz, buzz 或者 fizzbuzz。

In [27]:
# One-hot encode the desired outputs: [number, "fizz", "buzz", "fizzbuzz"]
def fizz_buzz_encode(i):
    if   i % 15 == 0: return 3
    elif i % 5  == 0: return 2
    elif i % 3  == 0: return 1
    else:             return 0
    
def fizz_buzz_decode(i, prediction):
    return [str(i), "fizz", "buzz", "fizzbuzz"][prediction]

print(fizz_buzz_decode(1, fizz_buzz_encode(1)))
print(fizz_buzz_decode(2, fizz_buzz_encode(2)))
print(fizz_buzz_decode(5, fizz_buzz_encode(5)))
print(fizz_buzz_decode(12, fizz_buzz_encode(12)))
print(fizz_buzz_decode(15, fizz_buzz_encode(15)))

1
2
buzz
fizz
fizzbuzz


我们首先定义模型的输入与输出(训练数据)

In [28]:
import numpy as np
import torch

NUM_DIGITS = 10

# Represent each input by an array of its binary digits.
def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])

trX = torch.Tensor([binary_encode(i, NUM_DIGITS) for i in range(101, 2 ** NUM_DIGITS)])
trY = torch.LongTensor([fizz_buzz_encode(i) for i in range(101, 2 ** NUM_DIGITS)])

然后我们用PyTorch定义模型

In [29]:
# Define the model
NUM_HIDDEN = 100
model = torch.nn.Sequential(
    torch.nn.Linear(NUM_DIGITS, NUM_HIDDEN),
    torch.nn.ReLU(),
    torch.nn.Linear(NUM_HIDDEN, 4)
)

- 为了让我们的模型学会FizzBuzz这个游戏，我们需要定义一个损失函数，和一个优化算法。
- 这个优化算法会不断优化（降低）损失函数，使得模型的在该任务上取得尽可能低的损失值。
- 损失值低往往表示我们的模型表现好，损失值高表示我们的模型表现差。
- 由于FizzBuzz游戏本质上是一个分类问题，我们选用Cross Entropyy Loss函数。
- 优化函数我们选用Stochastic Gradient Descent。

In [30]:
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.05)

以下是模型的训练代码

In [31]:
# Start training it
BATCH_SIZE = 128
for epoch in range(10000):
    for start in range(0, len(trX), BATCH_SIZE):
        end = start + BATCH_SIZE
        batchX = trX[start:end]
        batchY = trY[start:end]

        y_pred = model(batchX)
        loss = loss_fn(y_pred, batchY)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Find loss on training data
    loss = loss_fn(model(trX), trY).item()
    print('Epoch:', epoch, 'Loss:', loss)

Epoch: 0 Loss: 1.1863759756088257
Epoch: 1 Loss: 1.157894492149353
Epoch: 2 Loss: 1.1498943567276
Epoch: 3 Loss: 1.1466518640518188
Epoch: 4 Loss: 1.1449916362762451
Epoch: 5 Loss: 1.143990159034729
Epoch: 6 Loss: 1.143303394317627
Epoch: 7 Loss: 1.142789602279663
Epoch: 8 Loss: 1.1423760652542114
Epoch: 9 Loss: 1.1420289278030396
Epoch: 10 Loss: 1.141723394393921
Epoch: 11 Loss: 1.141450047492981
Epoch: 12 Loss: 1.1412018537521362
Epoch: 13 Loss: 1.1409754753112793
Epoch: 14 Loss: 1.1407641172409058
Epoch: 15 Loss: 1.1405678987503052
Epoch: 16 Loss: 1.1403822898864746
Epoch: 17 Loss: 1.1402071714401245
Epoch: 18 Loss: 1.1400408744812012
Epoch: 19 Loss: 1.1398837566375732
Epoch: 20 Loss: 1.1397329568862915
Epoch: 21 Loss: 1.139588713645935
Epoch: 22 Loss: 1.1394506692886353
Epoch: 23 Loss: 1.139319896697998
Epoch: 24 Loss: 1.1391912698745728
Epoch: 25 Loss: 1.1390684843063354
Epoch: 26 Loss: 1.1389490365982056
Epoch: 27 Loss: 1.138834834098816
Epoch: 28 Loss: 1.138723611831665
Epoch: 2

Epoch: 235 Loss: 1.1243518590927124
Epoch: 236 Loss: 1.1242260932922363
Epoch: 237 Loss: 1.1241044998168945
Epoch: 238 Loss: 1.123986005783081
Epoch: 239 Loss: 1.12385892868042
Epoch: 240 Loss: 1.123731255531311
Epoch: 241 Loss: 1.1236205101013184
Epoch: 242 Loss: 1.123486876487732
Epoch: 243 Loss: 1.1233718395233154
Epoch: 244 Loss: 1.1232503652572632
Epoch: 245 Loss: 1.1231154203414917
Epoch: 246 Loss: 1.1229811906814575
Epoch: 247 Loss: 1.1228554248809814
Epoch: 248 Loss: 1.1227210760116577
Epoch: 249 Loss: 1.1225866079330444
Epoch: 250 Loss: 1.1224478483200073
Epoch: 251 Loss: 1.1223106384277344
Epoch: 252 Loss: 1.122177004814148
Epoch: 253 Loss: 1.1220247745513916
Epoch: 254 Loss: 1.1218791007995605
Epoch: 255 Loss: 1.1217379570007324
Epoch: 256 Loss: 1.1215908527374268
Epoch: 257 Loss: 1.121443271636963
Epoch: 258 Loss: 1.121286153793335
Epoch: 259 Loss: 1.1211326122283936
Epoch: 260 Loss: 1.1209757328033447
Epoch: 261 Loss: 1.1208267211914062
Epoch: 262 Loss: 1.1206504106521606


Epoch: 477 Loss: 1.0169470310211182
Epoch: 478 Loss: 1.0164058208465576
Epoch: 479 Loss: 1.0156841278076172
Epoch: 480 Loss: 1.015245795249939
Epoch: 481 Loss: 1.0140904188156128
Epoch: 482 Loss: 1.0138357877731323
Epoch: 483 Loss: 1.0129069089889526
Epoch: 484 Loss: 1.0119367837905884
Epoch: 485 Loss: 1.0111967325210571
Epoch: 486 Loss: 1.0102176666259766
Epoch: 487 Loss: 1.009842038154602
Epoch: 488 Loss: 1.0088571310043335
Epoch: 489 Loss: 1.0086297988891602
Epoch: 490 Loss: 1.0071672201156616
Epoch: 491 Loss: 1.0068907737731934
Epoch: 492 Loss: 1.0057222843170166
Epoch: 493 Loss: 1.0049949884414673
Epoch: 494 Loss: 1.0045706033706665
Epoch: 495 Loss: 1.0041097402572632
Epoch: 496 Loss: 1.0033283233642578
Epoch: 497 Loss: 1.0022178888320923
Epoch: 498 Loss: 1.0014426708221436
Epoch: 499 Loss: 1.0003271102905273
Epoch: 500 Loss: 1.000455379486084
Epoch: 501 Loss: 0.9996194243431091
Epoch: 502 Loss: 0.9984729290008545
Epoch: 503 Loss: 1.0009974241256714
Epoch: 504 Loss: 0.997575283050

Epoch: 706 Loss: 0.8089808821678162
Epoch: 707 Loss: 0.8104071617126465
Epoch: 708 Loss: 0.8067026138305664
Epoch: 709 Loss: 0.8088684678077698
Epoch: 710 Loss: 0.8047152757644653
Epoch: 711 Loss: 0.8059985041618347
Epoch: 712 Loss: 0.8031206727027893
Epoch: 713 Loss: 0.8029946684837341
Epoch: 714 Loss: 0.800683319568634
Epoch: 715 Loss: 0.8016392588615417
Epoch: 716 Loss: 0.7986423373222351
Epoch: 717 Loss: 0.7988008856773376
Epoch: 718 Loss: 0.7977583408355713
Epoch: 719 Loss: 0.7947818040847778
Epoch: 720 Loss: 0.7966616153717041
Epoch: 721 Loss: 0.7928966283798218
Epoch: 722 Loss: 0.7956968545913696
Epoch: 723 Loss: 0.7919869422912598
Epoch: 724 Loss: 0.7916623950004578
Epoch: 725 Loss: 0.7900850772857666
Epoch: 726 Loss: 0.7895097732543945
Epoch: 727 Loss: 0.7883893847465515
Epoch: 728 Loss: 0.7864912748336792
Epoch: 729 Loss: 0.7869855165481567
Epoch: 730 Loss: 0.7848015427589417
Epoch: 731 Loss: 0.7843725085258484
Epoch: 732 Loss: 0.7833723425865173
Epoch: 733 Loss: 0.7817403078

Epoch: 942 Loss: 0.5768752694129944
Epoch: 943 Loss: 0.5766890645027161
Epoch: 944 Loss: 0.574909508228302
Epoch: 945 Loss: 0.5747119784355164
Epoch: 946 Loss: 0.5732300281524658
Epoch: 947 Loss: 0.5732151865959167
Epoch: 948 Loss: 0.5713380575180054
Epoch: 949 Loss: 0.5713919401168823
Epoch: 950 Loss: 0.5702218413352966
Epoch: 951 Loss: 0.5690693259239197
Epoch: 952 Loss: 0.5682777166366577
Epoch: 953 Loss: 0.5681558847427368
Epoch: 954 Loss: 0.5673319697380066
Epoch: 955 Loss: 0.5662036538124084
Epoch: 956 Loss: 0.5652552843093872
Epoch: 957 Loss: 0.5641111135482788
Epoch: 958 Loss: 0.5636101961135864
Epoch: 959 Loss: 0.5629693865776062
Epoch: 960 Loss: 0.5614902377128601
Epoch: 961 Loss: 0.5607122182846069
Epoch: 962 Loss: 0.5602133870124817
Epoch: 963 Loss: 0.559083878993988
Epoch: 964 Loss: 0.558386504650116
Epoch: 965 Loss: 0.557803213596344
Epoch: 966 Loss: 0.5569421648979187
Epoch: 967 Loss: 0.5554912090301514
Epoch: 968 Loss: 0.5554984211921692
Epoch: 969 Loss: 0.5535005331039

Epoch: 1171 Loss: 0.41417765617370605
Epoch: 1172 Loss: 0.4141392111778259
Epoch: 1173 Loss: 0.4130527079105377
Epoch: 1174 Loss: 0.4125176966190338
Epoch: 1175 Loss: 0.41161713004112244
Epoch: 1176 Loss: 0.4111669659614563
Epoch: 1177 Loss: 0.41089871525764465
Epoch: 1178 Loss: 0.4098060727119446
Epoch: 1179 Loss: 0.4094087779521942
Epoch: 1180 Loss: 0.4089564383029938
Epoch: 1181 Loss: 0.40804198384284973
Epoch: 1182 Loss: 0.40796804428100586
Epoch: 1183 Loss: 0.40726423263549805
Epoch: 1184 Loss: 0.4063868820667267
Epoch: 1185 Loss: 0.4060220718383789
Epoch: 1186 Loss: 0.4052112400531769
Epoch: 1187 Loss: 0.4045411944389343
Epoch: 1188 Loss: 0.4041464626789093
Epoch: 1189 Loss: 0.403473824262619
Epoch: 1190 Loss: 0.4029342234134674
Epoch: 1191 Loss: 0.40284866094589233
Epoch: 1192 Loss: 0.4018949866294861
Epoch: 1193 Loss: 0.40180134773254395
Epoch: 1194 Loss: 0.4005822539329529
Epoch: 1195 Loss: 0.40030086040496826
Epoch: 1196 Loss: 0.3991815745830536
Epoch: 1197 Loss: 0.3986361026

Epoch: 1402 Loss: 0.29939204454421997
Epoch: 1403 Loss: 0.29862555861473083
Epoch: 1404 Loss: 0.29839155077934265
Epoch: 1405 Loss: 0.2978818416595459
Epoch: 1406 Loss: 0.29752880334854126
Epoch: 1407 Loss: 0.29764828085899353
Epoch: 1408 Loss: 0.296686589717865
Epoch: 1409 Loss: 0.2964232861995697
Epoch: 1410 Loss: 0.29574665427207947
Epoch: 1411 Loss: 0.2957584857940674
Epoch: 1412 Loss: 0.29485228657722473
Epoch: 1413 Loss: 0.29470449686050415
Epoch: 1414 Loss: 0.2943603992462158
Epoch: 1415 Loss: 0.29390591382980347
Epoch: 1416 Loss: 0.29357513785362244
Epoch: 1417 Loss: 0.2933928668498993
Epoch: 1418 Loss: 0.2927872836589813
Epoch: 1419 Loss: 0.2922026216983795
Epoch: 1420 Loss: 0.29222404956817627
Epoch: 1421 Loss: 0.29159119725227356
Epoch: 1422 Loss: 0.2912271320819855
Epoch: 1423 Loss: 0.29068514704704285
Epoch: 1424 Loss: 0.29047834873199463
Epoch: 1425 Loss: 0.2899259626865387
Epoch: 1426 Loss: 0.2897847294807434
Epoch: 1427 Loss: 0.2894900441169739
Epoch: 1428 Loss: 0.28894

Epoch: 1627 Loss: 0.22674560546875
Epoch: 1628 Loss: 0.22668349742889404
Epoch: 1629 Loss: 0.2263282835483551
Epoch: 1630 Loss: 0.2261933535337448
Epoch: 1631 Loss: 0.22580178081989288
Epoch: 1632 Loss: 0.22570860385894775
Epoch: 1633 Loss: 0.22543734312057495
Epoch: 1634 Loss: 0.2251395583152771
Epoch: 1635 Loss: 0.22485210001468658
Epoch: 1636 Loss: 0.2246858775615692
Epoch: 1637 Loss: 0.22418570518493652
Epoch: 1638 Loss: 0.22408628463745117
Epoch: 1639 Loss: 0.22388315200805664
Epoch: 1640 Loss: 0.22342777252197266
Epoch: 1641 Loss: 0.22338324785232544
Epoch: 1642 Loss: 0.2229192554950714
Epoch: 1643 Loss: 0.22274376451969147
Epoch: 1644 Loss: 0.22254346311092377
Epoch: 1645 Loss: 0.2222624570131302
Epoch: 1646 Loss: 0.22198820114135742
Epoch: 1647 Loss: 0.22187311947345734
Epoch: 1648 Loss: 0.22135613858699799
Epoch: 1649 Loss: 0.2214001566171646
Epoch: 1650 Loss: 0.22109432518482208
Epoch: 1651 Loss: 0.22070461511611938
Epoch: 1652 Loss: 0.22048650681972504
Epoch: 1653 Loss: 0.22

Epoch: 1853 Loss: 0.17884890735149384
Epoch: 1854 Loss: 0.17870470881462097
Epoch: 1855 Loss: 0.1785806566476822
Epoch: 1856 Loss: 0.17833738029003143
Epoch: 1857 Loss: 0.1781667023897171
Epoch: 1858 Loss: 0.17819958925247192
Epoch: 1859 Loss: 0.17786657810211182
Epoch: 1860 Loss: 0.17756561934947968
Epoch: 1861 Loss: 0.1775447428226471
Epoch: 1862 Loss: 0.17735233902931213
Epoch: 1863 Loss: 0.17718777060508728
Epoch: 1864 Loss: 0.17704997956752777
Epoch: 1865 Loss: 0.17674113810062408
Epoch: 1866 Loss: 0.17658349871635437
Epoch: 1867 Loss: 0.17650727927684784
Epoch: 1868 Loss: 0.17637978494167328
Epoch: 1869 Loss: 0.17611035704612732
Epoch: 1870 Loss: 0.17586664855480194
Epoch: 1871 Loss: 0.17589786648750305
Epoch: 1872 Loss: 0.17563015222549438
Epoch: 1873 Loss: 0.17554159462451935
Epoch: 1874 Loss: 0.17527280747890472
Epoch: 1875 Loss: 0.17503415048122406
Epoch: 1876 Loss: 0.17505910992622375
Epoch: 1877 Loss: 0.17476093769073486
Epoch: 1878 Loss: 0.17462843656539917
Epoch: 1879 Los

Epoch: 2084 Loss: 0.14500771462917328
Epoch: 2085 Loss: 0.14479458332061768
Epoch: 2086 Loss: 0.14463625848293304
Epoch: 2087 Loss: 0.14454081654548645
Epoch: 2088 Loss: 0.1444566398859024
Epoch: 2089 Loss: 0.14431659877300262
Epoch: 2090 Loss: 0.14415238797664642
Epoch: 2091 Loss: 0.14405903220176697
Epoch: 2092 Loss: 0.1438966691493988
Epoch: 2093 Loss: 0.1437695324420929
Epoch: 2094 Loss: 0.14366938173770905
Epoch: 2095 Loss: 0.1435183435678482
Epoch: 2096 Loss: 0.14344394207000732
Epoch: 2097 Loss: 0.1433134824037552
Epoch: 2098 Loss: 0.1431715190410614
Epoch: 2099 Loss: 0.1430383324623108
Epoch: 2100 Loss: 0.14290861785411835
Epoch: 2101 Loss: 0.14282990992069244
Epoch: 2102 Loss: 0.14267833530902863
Epoch: 2103 Loss: 0.14252060651779175
Epoch: 2104 Loss: 0.14244794845581055
Epoch: 2105 Loss: 0.1423359513282776
Epoch: 2106 Loss: 0.1421981006860733
Epoch: 2107 Loss: 0.142067551612854
Epoch: 2108 Loss: 0.14189712703227997
Epoch: 2109 Loss: 0.14187049865722656
Epoch: 2110 Loss: 0.141

Epoch: 2302 Loss: 0.12094835191965103
Epoch: 2303 Loss: 0.12082891911268234
Epoch: 2304 Loss: 0.12072534114122391
Epoch: 2305 Loss: 0.12065427005290985
Epoch: 2306 Loss: 0.12057747691869736
Epoch: 2307 Loss: 0.12043754756450653
Epoch: 2308 Loss: 0.12038204073905945
Epoch: 2309 Loss: 0.12027539312839508
Epoch: 2310 Loss: 0.1201474666595459
Epoch: 2311 Loss: 0.12011440843343735
Epoch: 2312 Loss: 0.12001331150531769
Epoch: 2313 Loss: 0.11988004297018051
Epoch: 2314 Loss: 0.11981222033500671
Epoch: 2315 Loss: 0.11968223005533218
Epoch: 2316 Loss: 0.11963416635990143
Epoch: 2317 Loss: 0.11959797888994217
Epoch: 2318 Loss: 0.1194261908531189
Epoch: 2319 Loss: 0.11933813244104385
Epoch: 2320 Loss: 0.11927976459264755
Epoch: 2321 Loss: 0.11914707720279694
Epoch: 2322 Loss: 0.11906152963638306
Epoch: 2323 Loss: 0.11897692829370499
Epoch: 2324 Loss: 0.11889945715665817
Epoch: 2325 Loss: 0.11876726150512695
Epoch: 2326 Loss: 0.11878830939531326
Epoch: 2327 Loss: 0.11858037859201431
Epoch: 2328 Lo

Epoch: 2522 Loss: 0.10196613520383835
Epoch: 2523 Loss: 0.10189534723758698
Epoch: 2524 Loss: 0.10180655121803284
Epoch: 2525 Loss: 0.10179479420185089
Epoch: 2526 Loss: 0.10169700533151627
Epoch: 2527 Loss: 0.10156562179327011
Epoch: 2528 Loss: 0.10150012373924255
Epoch: 2529 Loss: 0.1015271246433258
Epoch: 2530 Loss: 0.10137586295604706
Epoch: 2531 Loss: 0.10125355422496796
Epoch: 2532 Loss: 0.10121708363294601
Epoch: 2533 Loss: 0.1011032685637474
Epoch: 2534 Loss: 0.101102314889431
Epoch: 2535 Loss: 0.1009720116853714
Epoch: 2536 Loss: 0.10090232640504837
Epoch: 2537 Loss: 0.10086604952812195
Epoch: 2538 Loss: 0.10076442360877991
Epoch: 2539 Loss: 0.10071643441915512
Epoch: 2540 Loss: 0.10058549046516418
Epoch: 2541 Loss: 0.10049436241388321
Epoch: 2542 Loss: 0.10044986009597778
Epoch: 2543 Loss: 0.10034430027008057
Epoch: 2544 Loss: 0.10030896216630936
Epoch: 2545 Loss: 0.10021300613880157
Epoch: 2546 Loss: 0.10015030950307846
Epoch: 2547 Loss: 0.10009554773569107
Epoch: 2548 Loss:

Epoch: 2747 Loss: 0.08582881093025208
Epoch: 2748 Loss: 0.0857662782073021
Epoch: 2749 Loss: 0.08567773550748825
Epoch: 2750 Loss: 0.08563879132270813
Epoch: 2751 Loss: 0.08557826280593872
Epoch: 2752 Loss: 0.08553162217140198
Epoch: 2753 Loss: 0.08547022938728333
Epoch: 2754 Loss: 0.08538629859685898
Epoch: 2755 Loss: 0.08532965928316116
Epoch: 2756 Loss: 0.08527617156505585
Epoch: 2757 Loss: 0.08518342673778534
Epoch: 2758 Loss: 0.0851394534111023
Epoch: 2759 Loss: 0.08507613837718964
Epoch: 2760 Loss: 0.08500506728887558
Epoch: 2761 Loss: 0.08496491611003876
Epoch: 2762 Loss: 0.08490445464849472
Epoch: 2763 Loss: 0.08489058166742325
Epoch: 2764 Loss: 0.08478289842605591
Epoch: 2765 Loss: 0.08472540974617004
Epoch: 2766 Loss: 0.08464295417070389
Epoch: 2767 Loss: 0.08458083868026733
Epoch: 2768 Loss: 0.08453255146741867
Epoch: 2769 Loss: 0.08445384353399277
Epoch: 2770 Loss: 0.08441763371229172
Epoch: 2771 Loss: 0.08430495113134384
Epoch: 2772 Loss: 0.0842999517917633
Epoch: 2773 Los

Epoch: 2965 Loss: 0.07356490939855576
Epoch: 2966 Loss: 0.07354529947042465
Epoch: 2967 Loss: 0.07350584864616394
Epoch: 2968 Loss: 0.07340973615646362
Epoch: 2969 Loss: 0.07335770130157471
Epoch: 2970 Loss: 0.07330495119094849
Epoch: 2971 Loss: 0.07325077801942825
Epoch: 2972 Loss: 0.07318269461393356
Epoch: 2973 Loss: 0.07317445427179337
Epoch: 2974 Loss: 0.07309599965810776
Epoch: 2975 Loss: 0.07305600494146347
Epoch: 2976 Loss: 0.07301383465528488
Epoch: 2977 Loss: 0.07298077642917633
Epoch: 2978 Loss: 0.07291411608457565
Epoch: 2979 Loss: 0.0728539228439331
Epoch: 2980 Loss: 0.07278301566839218
Epoch: 2981 Loss: 0.07276879996061325
Epoch: 2982 Loss: 0.07269257307052612
Epoch: 2983 Loss: 0.07265006005764008
Epoch: 2984 Loss: 0.07264236360788345
Epoch: 2985 Loss: 0.07255671918392181
Epoch: 2986 Loss: 0.07255373150110245
Epoch: 2987 Loss: 0.07245618104934692
Epoch: 2988 Loss: 0.07243408262729645
Epoch: 2989 Loss: 0.07237093895673752
Epoch: 2990 Loss: 0.0723646730184555
Epoch: 2991 Lo

Epoch: 3185 Loss: 0.06357269734144211
Epoch: 3186 Loss: 0.06353369355201721
Epoch: 3187 Loss: 0.06349340081214905
Epoch: 3188 Loss: 0.06345989555120468
Epoch: 3189 Loss: 0.06341288238763809
Epoch: 3190 Loss: 0.0634339302778244
Epoch: 3191 Loss: 0.0633382797241211
Epoch: 3192 Loss: 0.06330052018165588
Epoch: 3193 Loss: 0.06323433667421341
Epoch: 3194 Loss: 0.06322506815195084
Epoch: 3195 Loss: 0.06316656619310379
Epoch: 3196 Loss: 0.06319136172533035
Epoch: 3197 Loss: 0.06311500072479248
Epoch: 3198 Loss: 0.0630607008934021
Epoch: 3199 Loss: 0.06301185488700867
Epoch: 3200 Loss: 0.06297914683818817
Epoch: 3201 Loss: 0.06294315308332443
Epoch: 3202 Loss: 0.06290165334939957
Epoch: 3203 Loss: 0.06283605098724365
Epoch: 3204 Loss: 0.06281360238790512
Epoch: 3205 Loss: 0.06276153773069382
Epoch: 3206 Loss: 0.06276555359363556
Epoch: 3207 Loss: 0.06268615275621414
Epoch: 3208 Loss: 0.06269682198762894
Epoch: 3209 Loss: 0.06260818988084793
Epoch: 3210 Loss: 0.0625920370221138
Epoch: 3211 Loss

Epoch: 3414 Loss: 0.05518385395407677
Epoch: 3415 Loss: 0.05515581741929054
Epoch: 3416 Loss: 0.05510089918971062
Epoch: 3417 Loss: 0.05507148429751396
Epoch: 3418 Loss: 0.055032409727573395
Epoch: 3419 Loss: 0.055004190653562546
Epoch: 3420 Loss: 0.05498422682285309
Epoch: 3421 Loss: 0.05494361370801926
Epoch: 3422 Loss: 0.05491350591182709
Epoch: 3423 Loss: 0.05486806482076645
Epoch: 3424 Loss: 0.054837729781866074
Epoch: 3425 Loss: 0.05482647940516472
Epoch: 3426 Loss: 0.05478033423423767
Epoch: 3427 Loss: 0.05474850907921791
Epoch: 3428 Loss: 0.05471814051270485
Epoch: 3429 Loss: 0.054683517664670944
Epoch: 3430 Loss: 0.05466316640377045
Epoch: 3431 Loss: 0.054595593363046646
Epoch: 3432 Loss: 0.054579559713602066
Epoch: 3433 Loss: 0.054536182433366776
Epoch: 3434 Loss: 0.05453020706772804
Epoch: 3435 Loss: 0.05447082221508026
Epoch: 3436 Loss: 0.05447249487042427
Epoch: 3437 Loss: 0.05440276488661766
Epoch: 3438 Loss: 0.05441807582974434
Epoch: 3439 Loss: 0.05435502529144287
Epoch

Epoch: 3629 Loss: 0.04869323596358299
Epoch: 3630 Loss: 0.04866374284029007
Epoch: 3631 Loss: 0.04861191287636757
Epoch: 3632 Loss: 0.0486217699944973
Epoch: 3633 Loss: 0.04858650639653206
Epoch: 3634 Loss: 0.048589807003736496
Epoch: 3635 Loss: 0.0485529787838459
Epoch: 3636 Loss: 0.0485168918967247
Epoch: 3637 Loss: 0.04846867918968201
Epoch: 3638 Loss: 0.04847374185919762
Epoch: 3639 Loss: 0.04844004288315773
Epoch: 3640 Loss: 0.04842530936002731
Epoch: 3641 Loss: 0.048388298600912094
Epoch: 3642 Loss: 0.0483526811003685
Epoch: 3643 Loss: 0.04832077398896217
Epoch: 3644 Loss: 0.04829636588692665
Epoch: 3645 Loss: 0.048253320157527924
Epoch: 3646 Loss: 0.048239342868328094
Epoch: 3647 Loss: 0.048190582543611526
Epoch: 3648 Loss: 0.048195064067840576
Epoch: 3649 Loss: 0.048155881464481354
Epoch: 3650 Loss: 0.0481334887444973
Epoch: 3651 Loss: 0.048104576766490936
Epoch: 3652 Loss: 0.04809153452515602
Epoch: 3653 Loss: 0.04806551709771156
Epoch: 3654 Loss: 0.04802782088518143
Epoch: 36

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Users/zeweichu/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-c2cf5b37f087>", line 9, in <module>
    y_pred = model(batchX)
  File "/Users/zeweichu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/zeweichu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/zeweichu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/zeweichu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/Users/zeweichu/anaconda3/en

KeyboardInterrupt: 

最后我们用训练好的模型尝试在1到100这些数字上玩FizzBuzz游戏

In [ ]:
# Output now
testX = torch.Tensor([binary_encode(i, NUM_DIGITS) for i in range(1, 101)])
with torch.no_grad():
    testY = model(testX)
predictions = zip(range(1, 101), list(testY.max(1)[1].data.tolist()))

print([fizz_buzz_decode(i, x) for (i, x) in predictions])

In [ ]:
print(np.sum(testY.max(1)[1].numpy() == np.array([fizz_buzz_encode(i) for i in range(1,101)])))
testY.max(1)[1].numpy() == np.array([fizz_buzz_encode(i) for i in range(1,101)])